### ISSUE TITLE
win11 上的 Mac 虚拟机运行这个，报同样的错怎么回事 ？

### ISSUE THREAD

**Issue by chen19890425** [okkoye/ByteSync#2]
Mac  11
XCode  12.5.1
visual studio 2022 for mac

报下面的错：
error.Description "Error Domain=NSFileProviderErrorDomain Code=-2001 \"应用程序目前无法使用。\" UserInfo={NSLocalizedDescription=应用程序目前无法使用。}"

**Comment by ohyex** [comment]
你这个用的是 arm64 芯片吗？

**Comment by chen19890425** [comment]
Inter 的
